### ISSUE TITLE
Running HelloWorld in Nexus 5

### ISSUE THREAD

**Issue by raj2sudha1** [silklabs/silk#21]
code in index.js ---
'use strict';
const log = require('silk-alog');
log.info('hello world');
--------------------------------------Here is issue i am facing -----
raj@raj-VirtualBox:~/learning/examples/first1$ silk run
[silk-cli] FATAL : Failed to execute 'run' on plugin '/home/raj/learning/examples/first1/node_modules/silk/cli.js' Error: An error occured while running: adb root Error: Command failed: adb root

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
    at /home/raj/learning/examples/first1/node_modules/silk/build/api.js:32:13
    at throw (native)
    at step (/home/raj/learning/examples/first1/node_modules/silk/build/api.js:61:191)
    at /home/raj/learning/examples/first1/node_modules/silk/build/api.js:61:402
raj@raj-VirtualBox:~/learning/examples/first1$ adb root
adbd is already running as root

**Comment by raj2sudha1** [comment]
After rebuilding the images and flashed them manually, everything started working.
